.section .text.n_funcs_$$_AnsiCompareStr,"x"
	.balign 16,0x90
.globl	FUNCS_$$_ANSICOMPARESTR
FUNCS_$$_ANSICOMPARESTR:
ret

.section .text.n_funcs_$$_AnsiCompareText,"x"
	.balign 16,0x90
.globl	FUNCS_$$_ANSICOMPARETEXT
FUNCS_$$_ANSICOMPARETEXT:
ret


/*
global AnsiExtractQuotedStr
AnsiExtractQuotedStr:
ret

global AnsiLastChar
AnsiLastChar:
ret

global AnsiLowerCase
AnsiLowerCase:
ret

global AnsiQuotedStr
AnsiQuotedStr:
ret

global AnsiStrComp
AnsiStrComp:
ret

global AnsiStrIComp
AnsiStrIComp:
ret

global AnsiStrLComp
AnsiStrLComp:
ret

global AnsiStrLIComp
AnsiStrLIComp:
ret

global AnsiStrLastChar
AnsiStrLastChar:
ret

global AnsiStrLower
AnsiStrLower:
ret

global AnsiStrUpper
AnsiStrUpper:
ret

global AnsiUpperCase
AnsiUpperCase:
ret

global AppendStr
AppendStr:
ret

global AssignStr
AssignStr:
ret

global CompareStr
CompareStr:
ret

global CompareText
CompareText:
ret

global DisposeStr
DisposeStr:
ret

global IsValidIdent
IsValidIdent:
ret

global LastDelimiter
LastDelimiter:
ret

global LeftStr
LeftStr:
ret

global LoadStr
LoadStr:
ret

global LowerCase
LowerCase:
ret

global NewStr
NewStr:
ret

global RightStr
RightStr:
ret

global StrAlloc
StrAlloc:
ret

global StrBufSize
StrBufSize:
ret

global StrDispose
StrDispose:
ret

global StrPas
StrPas:
ret

global StrPCopy
StrPCopy:
ret

global StrPLCopy
StrPLCopy:
ret

global UpperCase
UpperCase:
ret

global IntToStr
IntToStr:
ret

global StrToInt
StrToInt:
ret
*/

.section .text.n_funcs_$$_StrToInt,"x"
	.balign 16,0x90
.globl	FUNCS_$$_StrToInt
FUNCS_$$_StrToInt:
ret
